Makefile.am: fix parallel issue w/ tools
nciattach requires generated local_headers too

In file included from tools/nciattach.c:47:
./src/near.h:41:10: fatal error: near/dbus.h: No such file or directory
   41 | #include <near/dbus.h>
         |          ^~~~~~~~~~~~~
	 compilation terminated.

Signed-off-by: Nicolas PARLANT <nicolas.parlant@parhuet.fr>
Signed-off-by: Krzysztof Kozlowski <krzk@kernel.org>